from gi.repository import Gimp, Gtk, GLib, Gdk # type: ignore
from gi.repository.GdkPixbuf import Pixbuf # type: ignore
import os

from label import AIHubLabel

class AboutDialog(Gtk.Dialog):
    def __init__(self, parent, version):
        super().__init__(title="About Gimp AIHub", parent=parent, flags=0)
        self.set_default_size(400, 300)

        self.set_keep_above(True)

        content_area = self.get_content_area()
        content_box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=10)
        content_box.set_border_width(10)
        content_area.add(content_box)

        content_box.pack_start(Gtk.Label(label="GIMP AIHub Version: " + (version if version else "unknown")), False, False, 0)

        OOPISTO_IMAGE = Pixbuf.new_from_file_at_scale(
            os.path.join(os.path.dirname(os.path.abspath(__file__)), "logo", "oopisto.png"),
            200,
            200,
            True,
        )

        oopisto_logo = Gtk.Image.new_from_pixbuf(OOPISTO_IMAGE)

        content_box.pack_start(oopisto_logo, False, False, 0)

        OOPISTO_URL = "https://otavanopisto.fi/"

        # add the url link
        link_button = Gtk.LinkButton(uri=OOPISTO_URL, label="https://otavanopisto.fi/")
        content_box.pack_start(link_button, False, False, 0)

        # Add information about license
        license_label = Gtk.Label(label="GIMP AIHub is licensed under the GNU General Public License.")
        content_box.pack_start(license_label, False, False, 0)

        # Add a divider
        separator = Gtk.Separator(orientation=Gtk.Orientation.HORIZONTAL)
        content_box.pack_start(separator, False, False, 10)

        extra_info = AIHubLabel("This product has been developed by Otavan Opisto in the city of Mikkeli, Finland; with the purpose of being an educational tool for students learning programming and AI concepts as well as facilitating teachers with AI content generation tools that they can access.")
        content_box.pack_start(extra_info.get_widget(), False, False, 0)

        extra_info_2 = AIHubLabel("Any use of the product is at your own risk. Otavan Opisto is not responsible for any damages or losses caused by the use of this product.")
        content_box.pack_start(extra_info_2.get_widget(), False, False, 0)

        extra_info_3 = AIHubLabel("Otavan Opisto is not responsible for any content generated by AI models or any actions taken based on such content, AIHub is merely a tool to facilitate access to AI models.")
        content_box.pack_start(extra_info_3.get_widget(), False, False, 0)

        self.add_button(Gtk.STOCK_CLOSE, Gtk.ResponseType.CLOSE)

        self.show_all()

    def on_close(self, callback):
        self.connect("response", lambda dialog, response: callback() or self.destroy())